/**
 * Groco Centralized Product Dataset
 * 40+ High-Quality Products Across 12 Grocery Categories
 */

const GROCO_PRODUCTS = [
  // FRUITS (1 - 5)
  {
    id: 'p1',
    name: 'Fresh Red Gala Apples',
    category: 'Fruits',
    categorySlug: 'fruits',
    price: 3.99,
    oldPrice: 4.99,
    rating: 4.9,
    reviews: 142,
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '1 kg / Pack',
    description: 'Sweet, crisp, and 100% organic Gala apples handpicked daily from certified sustainable orchards.'
  },
  {
    id: 'p2',
    name: 'Organic Cavendish Bananas',
    category: 'Fruits',
    categorySlug: 'fruits',
    price: 1.89,
    oldPrice: 2.49,
    rating: 4.8,
    reviews: 98,
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '1 Bunch (~1.2 kg)',
    description: 'Naturally sweet and rich in potassium, perfect for healthy morning smoothies or daily snacking.'
  },
  {
    id: 'p3',
    name: 'Fresh Tropical Mangoes',
    category: 'Fruits',
    categorySlug: 'fruits',
    price: 5.29,
    oldPrice: 6.49,
    rating: 4.9,
    reviews: 165,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80',
    badge: 'NEW',
    badgeType: 'new',
    unit: '3 Pack',
    description: 'Juicy, fragrant ripe Alphonso mangoes bursting with sweet tropical flavor and Vitamin A.'
  },
  {
    id: 'p4',
    name: 'Juicy Valencia Oranges',
    category: 'Fruits',
    categorySlug: 'fruits',
    price: 3.49,
    oldPrice: 4.29,
    rating: 4.7,
    reviews: 110,
    image: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&w=600&q=80',
    badge: 'SALE 18% OFF',
    badgeType: 'sale',
    unit: '1.5 kg Net Bag',
    description: 'Plump and extra juicy oranges loaded with fresh Vitamin C, ideal for fresh breakfast juice.'
  },
  {
    id: 'p5',
    name: 'Crisp Green Granny Smith Apples',
    category: 'Fruits',
    categorySlug: 'fruits',
    price: 4.19,
    oldPrice: 4.99,
    rating: 4.8,
    reviews: 84,
    image: 'https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '1 kg Pack',
    description: 'Tangy and crunchy green apples, fantastic for fresh salads, baking pies, or healthy snacking.'
  },

  // VEGETABLES (6 - 10)
  {
    id: 'p6',
    name: 'Fresh Farm Broccoli Crown',
    category: 'Vegetables',
    categorySlug: 'vegetables',
    price: 2.79,
    oldPrice: 3.49,
    rating: 4.7,
    reviews: 84,
    image: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '500g Head',
    description: 'Nutrient-rich green broccoli crowns sourced straight from local organic farm harvests.'
  },
  {
    id: 'p7',
    name: 'Crisp Organic Carrots',
    category: 'Vegetables',
    categorySlug: 'vegetables',
    price: 1.99,
    oldPrice: 2.59,
    rating: 4.8,
    reviews: 110,
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '1 kg Bag',
    description: 'Sweet and crunchy orange carrots high in Vitamin A, ideal for salads, roasting, or juicing.'
  },
  {
    id: 'p8',
    name: 'Vine Ripe Red Tomatoes',
    category: 'Vegetables',
    categorySlug: 'vegetables',
    price: 2.49,
    oldPrice: 3.19,
    rating: 4.6,
    reviews: 67,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    badge: 'NEW',
    badgeType: 'new',
    unit: '750g Pack',
    description: 'Plump, juicy vine-ripened tomatoes brimming with lycopene and rich natural flavor.'
  },
  {
    id: 'p9',
    name: 'Fresh Baby Spinach Leaves',
    category: 'Vegetables',
    categorySlug: 'vegetables',
    price: 2.99,
    oldPrice: 3.79,
    rating: 4.9,
    reviews: 130,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '250g Tub',
    description: 'Tender, pre-washed organic baby spinach packed with iron, folate, and essential vitamins.'
  },
  {
    id: 'p10',
    name: 'Mixed Sweet Bell Peppers',
    category: 'Vegetables',
    categorySlug: 'vegetables',
    price: 3.89,
    oldPrice: 4.69,
    rating: 4.8,
    reviews: 95,
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=600&q=80',
    badge: 'SALE 17% OFF',
    badgeType: 'sale',
    unit: '3 Pack (Red/Yellow/Green)',
    description: 'Vibrant, crunchy sweet bell peppers full of antioxidants, perfect for stir-fries and salads.'
  },

  // DAIRY & EGGS (11 - 15)
  {
    id: 'p11',
    name: 'Whole Organic Whole Milk',
    category: 'Dairy & Eggs',
    categorySlug: 'dairy',
    price: 3.89,
    oldPrice: 4.49,
    rating: 4.9,
    reviews: 210,
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '1 Gallon (3.78L)',
    description: 'Farm-fresh 100% grass-fed organic milk with no added hormones or synthetic antibiotics.'
  },
  {
    id: 'p12',
    name: 'Free-Range Organic Eggs',
    category: 'Dairy & Eggs',
    categorySlug: 'dairy',
    price: 4.29,
    oldPrice: 5.19,
    rating: 4.9,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '12 Count Carton',
    description: 'Certified humane free-range eggs with rich golden yolks from pasture-raised hens.'
  },
  {
    id: 'p13',
    name: 'Aged Mature Cheddar Cheese',
    category: 'Dairy & Eggs',
    categorySlug: 'dairy',
    price: 4.99,
    oldPrice: 6.29,
    rating: 4.8,
    reviews: 140,
    image: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=600&q=80',
    badge: 'NEW',
    badgeType: 'new',
    unit: '300g Block',
    description: 'Rich, sharp aged cheddar block crafted traditionally using pure English pasture milk.'
  },
  {
    id: 'p14',
    name: 'Greek Style Plain Yogurt',
    category: 'Dairy & Eggs',
    categorySlug: 'dairy',
    price: 3.49,
    oldPrice: 4.29,
    rating: 4.8,
    reviews: 124,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80',
    badge: 'SALE 18% OFF',
    badgeType: 'sale',
    unit: '500g Tub',
    description: 'Thick, creamy probiotic Greek yogurt strained naturally for protein-rich breakfasts.'
  },
  {
    id: 'p15',
    name: 'Pure European Creamery Butter',
    category: 'Dairy & Eggs',
    categorySlug: 'dairy',
    price: 3.99,
    oldPrice: 4.79,
    rating: 4.9,
    reviews: 175,
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '250g Block',
    description: 'Rich churned unsalted creamery butter with 82% butterfat for luscious cooking and baking.'
  },

  // BEVERAGES (16 - 20)
  {
    id: 'p16',
    name: 'Fresh Cold-Pressed Orange Juice',
    category: 'Beverages',
    categorySlug: 'beverages',
    price: 4.99,
    oldPrice: 6.29,
    rating: 4.8,
    reviews: 145,
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '1 Liter Bottle',
    description: '100% pure cold-pressed Valencia orange juice with naturally sweet pulp and no added sugar.'
  },
  {
    id: 'p17',
    name: 'Pressed Organic Apple Juice',
    category: 'Beverages',
    categorySlug: 'beverages',
    price: 4.29,
    oldPrice: 5.19,
    rating: 4.7,
    reviews: 90,
    image: 'https://images.unsplash.com/photo-1567103472667-6898f3a79cf2?auto=format&fit=crop&w=600&q=80',
    badge: 'NEW',
    badgeType: 'new',
    unit: '1 Liter Glass Bottle',
    description: 'Unfiltered, cloudy 100% pressed apple juice made from crisp orchard apples.'
  },
  {
    id: 'p18',
    name: 'Natural Sparkling Mineral Water',
    category: 'Beverages',
    categorySlug: 'beverages',
    price: 2.49,
    oldPrice: 3.19,
    rating: 4.9,
    reviews: 220,
    image: 'https://images.unsplash.com/photo-1559839914-17aae19cec71?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '750ml Glass Bottle',
    description: 'Refreshing sparkling spring mineral water bottled directly at alpine mountain sources.'
  },
  {
    id: 'p19',
    name: 'Detox Organic Green Juice',
    category: 'Beverages',
    categorySlug: 'beverages',
    price: 5.49,
    oldPrice: 6.79,
    rating: 4.8,
    reviews: 105,
    image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '500ml Bottle',
    description: 'Nutrient-packed cold-pressed blend of kale, cucumber, green apple, celery, and ginger.'
  },
  {
    id: 'p20',
    name: 'Artisanal Peach Iced Tea',
    category: 'Beverages',
    categorySlug: 'beverages',
    price: 3.29,
    oldPrice: 3.99,
    rating: 4.6,
    reviews: 78,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80',
    badge: 'SALE 17% OFF',
    badgeType: 'sale',
    unit: '500ml Bottle',
    description: 'Real brewed black tea infused with sweet natural peach extract and a hint of lemon.'
  },

  // BAKERY & BREAD (21 - 25)
  {
    id: 'p21',
    name: 'Whole Grain Brown Bread',
    category: 'Bakery & Bread',
    categorySlug: 'bakery',
    price: 3.49,
    oldPrice: 4.29,
    rating: 4.8,
    reviews: 140,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '600g Loaf',
    description: 'Soft whole grain brown bread baked fresh daily with hearty cracked wheat grains.'
  },
  {
    id: 'p22',
    name: 'Fresh French Butter Croissants',
    category: 'Bakery & Bread',
    categorySlug: 'bakery',
    price: 3.99,
    oldPrice: 4.89,
    rating: 4.9,
    reviews: 180,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
    badge: 'NEW',
    badgeType: 'new',
    unit: '4 Pack',
    description: 'Flaky, golden French butter croissants hand-crafted with pure European creamery butter.'
  },
  {
    id: 'p23',
    name: 'Fresh Blueberry Muffins',
    category: 'Bakery & Bread',
    categorySlug: 'bakery',
    price: 4.29,
    oldPrice: 5.19,
    rating: 4.8,
    reviews: 115,
    image: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '4 Pack',
    description: 'Moist bakery muffins loaded with sweet organic wild blueberries and sugar crumble.'
  },
  {
    id: 'p24',
    name: 'Rich Dark Chocolate Cake Slice',
    category: 'Bakery & Bread',
    categorySlug: 'bakery',
    price: 4.99,
    oldPrice: 5.99,
    rating: 4.9,
    reviews: 210,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '1 Slice (~200g)',
    description: 'Decadent layer chocolate fudge cake coated in rich Belgian dark chocolate ganache.'
  },
  {
    id: 'p25',
    name: 'Artisan Chocolate Chip Cookies',
    category: 'Bakery & Bread',
    categorySlug: 'bakery',
    price: 3.89,
    oldPrice: 4.69,
    rating: 4.7,
    reviews: 95,
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80',
    badge: 'SALE 17% OFF',
    badgeType: 'sale',
    unit: '8 Pack',
    description: 'Crispy edge, chewy center butter cookies studded with semi-sweet dark chocolate chunks.'
  },

  // SNACKS (26 - 30)
  {
    id: 'p26',
    name: 'Sea Salt Kettle Potato Chips',
    category: 'Snacks',
    categorySlug: 'snacks',
    price: 2.99,
    oldPrice: 3.69,
    rating: 4.7,
    reviews: 130,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '180g Bag',
    description: 'Thick-cut kettle cooked potato crisps seasoned with natural pink Himalayan sea salt.'
  },
  {
    id: 'p27',
    name: 'Butter Organic Popcorn',
    category: 'Snacks',
    categorySlug: 'snacks',
    price: 2.49,
    oldPrice: 3.19,
    rating: 4.6,
    reviews: 85,
    image: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=600&q=80',
    badge: 'NEW',
    badgeType: 'new',
    unit: '150g Bag',
    description: 'Lightly popped organic corn tossed in pure grass-fed butter and sea salt.'
  },
  {
    id: 'p28',
    name: 'Honey Oat Granola Bars',
    category: 'Snacks',
    categorySlug: 'snacks',
    price: 3.99,
    oldPrice: 4.89,
    rating: 4.8,
    reviews: 160,
    image: 'https://images.unsplash.com/photo-1622484210800-8851413a96ef?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '6 Pack Box',
    description: 'Chewy whole grain oat bars sweetened with raw wildflower honey and almonds.'
  },
  {
    id: 'p29',
    name: 'Roasted Salted Mixed Nuts',
    category: 'Snacks',
    categorySlug: 'snacks',
    price: 6.99,
    oldPrice: 8.49,
    rating: 4.9,
    reviews: 240,
    image: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '400g Can',
    description: 'Premium blend of roasted almonds, cashews, pecans, and pistachios with sea salt.'
  },
  {
    id: 'p30',
    name: 'Multigrain Seeded Rice Crackers',
    category: 'Snacks',
    categorySlug: 'snacks',
    price: 2.79,
    oldPrice: 3.49,
    rating: 4.6,
    reviews: 70,
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=600&q=80',
    badge: 'SALE 20% OFF',
    badgeType: 'sale',
    unit: '150g Box',
    description: 'Crispy oven-baked brown rice crackers loaded with sesame and flax seeds.'
  },

  // STAPLES & GRAINS (31 - 35)
  {
    id: 'p31',
    name: 'Royal Organic Basmati Rice',
    category: 'Staples & Grains',
    categorySlug: 'staples',
    price: 8.99,
    oldPrice: 10.99,
    rating: 4.9,
    reviews: 280,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '2 kg Bag',
    description: 'Extra-long grain aromatic aged organic Basmati rice harvested from Himalayan foothills.'
  },
  {
    id: 'p32',
    name: 'Whole Wheat Stoneground Flour',
    category: 'Staples & Grains',
    categorySlug: 'staples',
    price: 3.49,
    oldPrice: 4.29,
    rating: 4.8,
    reviews: 140,
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '2 kg Bag',
    description: '100% unbleached stoneground whole wheat flour for fresh rotis, breads, and baking.'
  },
  {
    id: 'p33',
    name: 'Split Yellow Lentils (Dal)',
    category: 'Staples & Grains',
    categorySlug: 'staples',
    price: 2.99,
    oldPrice: 3.69,
    rating: 4.7,
    reviews: 95,
    image: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80',
    badge: 'NEW',
    badgeType: 'new',
    unit: '1 kg Bag',
    description: 'High-protein organic split yellow lentils, easy to cook and digest for wholesome meals.'
  },
  {
    id: 'p34',
    name: 'Raw Organic Cane Sugar',
    category: 'Staples & Grains',
    categorySlug: 'staples',
    price: 2.79,
    oldPrice: 3.49,
    rating: 4.7,
    reviews: 110,
    image: 'https://images.unsplash.com/photo-1622484210800-8851413a96ef?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '1 kg Bag',
    description: 'Unrefined golden raw cane sugar with natural molasses flavor for beverages and desserts.'
  },
  {
    id: 'p35',
    name: 'Cold-Pressed Sunflower Oil',
    category: 'Staples & Grains',
    categorySlug: 'staples',
    price: 6.49,
    oldPrice: 7.99,
    rating: 4.8,
    reviews: 165,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    badge: 'SALE 18% OFF',
    badgeType: 'sale',
    unit: '1 Liter Bottle',
    description: '100% pure cold-pressed sunflower cooking oil high in Vitamin E with a light neutral taste.'
  },

  // MEAT & SEAFOOD (36 - 40)
  {
    id: 'p36',
    name: 'Fresh Organic Chicken Breast',
    category: 'Meat & Seafood',
    categorySlug: 'meat',
    price: 8.99,
    oldPrice: 10.99,
    rating: 4.8,
    reviews: 155,
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '500g Pack',
    description: 'Boneless, skinless air-chilled organic chicken breast raised on free-range pasture farms.'
  },
  {
    id: 'p37',
    name: 'Crispy Organic Chicken Wings',
    category: 'Meat & Seafood',
    categorySlug: 'meat',
    price: 7.49,
    oldPrice: 8.99,
    rating: 4.7,
    reviews: 110,
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=600&q=80',
    badge: 'NEW',
    badgeType: 'new',
    unit: '750g Pack',
    description: 'Fresh free-range chicken wings ready for roasting, baking, or air-frying.'
  },
  {
    id: 'p38',
    name: 'Grass-Fed Angus Beef Mince',
    category: 'Meat & Seafood',
    categorySlug: 'meat',
    price: 9.49,
    oldPrice: 11.29,
    rating: 4.7,
    reviews: 130,
    image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?auto=format&fit=crop&w=600&q=80',
    badge: 'SALE 16% OFF',
    badgeType: 'sale',
    unit: '500g Pack',
    description: '90/10 lean grass-fed Angus beef ground fresh daily without artificial additives.'
  },
  {
    id: 'p39',
    name: 'Wild Alaskan Salmon Fillet',
    category: 'Meat & Seafood',
    categorySlug: 'meat',
    price: 11.99,
    oldPrice: 14.49,
    rating: 4.9,
    reviews: 188,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '450g Portion',
    description: 'Sustainably wild-caught Alaskan sockeye salmon rich in Omega-3 fatty acids.'
  },
  {
    id: 'p40',
    name: 'Fresh Jumbo Tiger Prawns',
    category: 'Meat & Seafood',
    categorySlug: 'meat',
    price: 12.99,
    oldPrice: 15.99,
    rating: 4.8,
    reviews: 145,
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '400g Pack',
    description: 'Succulent peeled and deveined jumbo tiger prawns, ideal for grilling or garlic butter stir-fry.'
  },

  // FROZEN FOODS (41 - 44)
  {
    id: 'p41',
    name: 'Golden Crispy Frozen Fries',
    category: 'Frozen Foods',
    categorySlug: 'frozen',
    price: 3.49,
    oldPrice: 4.29,
    rating: 4.7,
    reviews: 140,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '750g Bag',
    description: 'Straight-cut oven bake or air-fry potato fries with a crispy golden crunch.'
  },
  {
    id: 'p42',
    name: 'Crispy Chicken Breast Nuggets',
    category: 'Frozen Foods',
    categorySlug: 'frozen',
    price: 4.99,
    oldPrice: 5.99,
    rating: 4.8,
    reviews: 165,
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
    badge: 'NEW',
    badgeType: 'new',
    unit: '500g Bag',
    description: '100% white meat chicken nuggets coated in seasoned crispy breadcrumbs.'
  },
  {
    id: 'p43',
    name: 'Sweet Garden Frozen Peas',
    category: 'Frozen Foods',
    categorySlug: 'frozen',
    price: 2.79,
    oldPrice: 3.49,
    rating: 4.6,
    reviews: 80,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '500g Bag',
    description: 'Tender sweet garden peas flash-frozen within hours of harvest to lock in natural flavor.'
  },
  {
    id: 'p44',
    name: 'Wood-Fired Veggie Frozen Pizza',
    category: 'Frozen Foods',
    categorySlug: 'frozen',
    price: 6.99,
    oldPrice: 8.49,
    rating: 4.7,
    reviews: 115,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    badge: 'SALE 17% OFF',
    badgeType: 'sale',
    unit: '420g Box',
    description: 'Thin crust wood-fired pizza topped with roasted bell peppers, mozzarella, and basil pesto.'
  },

  // SAUCES & CONDIMENTS (45 - 48)
  {
    id: 'p45',
    name: 'Organic Tomato Ketchup',
    category: 'Sauces & Condiments',
    categorySlug: 'sauces',
    price: 2.99,
    oldPrice: 3.69,
    rating: 4.8,
    reviews: 190,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '500g Bottle',
    description: 'Rich tomato ketchup made from 100% sun-ripened organic tomatoes with no high-fructose corn syrup.'
  },
  {
    id: 'p46',
    name: 'Real Creamy Mayonnaise',
    category: 'Sauces & Condiments',
    categorySlug: 'sauces',
    price: 3.49,
    oldPrice: 4.29,
    rating: 4.7,
    reviews: 125,
    image: 'https://images.unsplash.com/photo-1585670149967-b4f4da88cc9f?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '400g Jar',
    description: 'Rich and velvety mayonnaise made with 100% free-range eggs and cold-pressed oil.'
  },
  {
    id: 'p47',
    name: 'Spicy Garlic Chilli Sauce',
    category: 'Sauces & Condiments',
    categorySlug: 'sauces',
    price: 2.89,
    oldPrice: 3.59,
    rating: 4.8,
    reviews: 95,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
    badge: 'NEW',
    badgeType: 'new',
    unit: '300ml Bottle',
    description: 'Fiery red chilli sauce infused with crushed garlic and natural tangy vinegar.'
  },
  {
    id: 'p48',
    name: 'Smoky Hickory BBQ Sauce',
    category: 'Sauces & Condiments',
    categorySlug: 'sauces',
    price: 3.79,
    oldPrice: 4.49,
    rating: 4.9,
    reviews: 150,
    image: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?auto=format&fit=crop&w=600&q=80',
    badge: 'SALE 15% OFF',
    badgeType: 'sale',
    unit: '450g Bottle',
    description: 'Thick barbecue sauce slow-cooked with hickory wood smoke, brown sugar, and spices.'
  },

  // PERSONAL CARE (49 - 50)
  {
    id: 'p49',
    name: 'Nourishing Herbal Shampoo',
    category: 'Personal Care',
    categorySlug: 'personal',
    price: 5.99,
    oldPrice: 7.29,
    rating: 4.7,
    reviews: 110,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '400ml Bottle',
    description: 'Sulfate-free herbal shampoo infused with organic argan oil and botanical extracts.'
  },
  {
    id: 'p50',
    name: 'Organic Aloe Hand Wash',
    category: 'Personal Care',
    categorySlug: 'personal',
    price: 3.99,
    oldPrice: 4.99,
    rating: 4.8,
    reviews: 86,
    image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '350ml Pump',
    description: 'Moisturizing plant-based hand soap infused with soothing organic aloe vera and lavender.'
  },

  // HOME CARE (51 - 52)
  {
    id: 'p51',
    name: 'Eco-Friendly Plant Dish Wash',
    category: 'Home Care',
    categorySlug: 'home',
    price: 3.79,
    oldPrice: 4.69,
    rating: 4.8,
    reviews: 132,
    image: 'https://images.unsplash.com/photo-1585670149967-b4f4da88cc9f?auto=format&fit=crop&w=600&q=80',
    badge: 'BESTSELLER',
    badgeType: 'bestseller',
    unit: '750ml Bottle',
    description: 'Tough on grease dishwashing liquid crafted with 100% biodegradable plant surfactants.'
  },
  {
    id: 'p52',
    name: 'Citrus Surface Cleaner Spray',
    category: 'Home Care',
    categorySlug: 'home',
    price: 4.29,
    oldPrice: 5.19,
    rating: 4.7,
    reviews: 94,
    image: 'https://images.unsplash.com/photo-1584813470613-5a1c6cbd3d1e?auto=format&fit=crop&w=600&q=80',
    badge: 'ORGANIC',
    badgeType: 'organic',
    unit: '500ml Spray',
    description: 'Non-toxic citrus multi-surface cleaner that cuts through grime leaving a fresh lemon scent.'
  }
];

// Helper Functions
function getProductById(id) {
  if (!id) return null;
  return GROCO_PRODUCTS.find(p => String(p.id).toLowerCase() === String(id).toLowerCase());
}

function getFeaturedProducts() {
  return GROCO_PRODUCTS.slice(0, 8);
}
